//The follwoing was generated by chatgpt to create test data
// can input variable values to change the shape 
#include <stdio.h>

#define ROWS 101
#define COLS 100

int main() {
    FILE *file;
    int i, j;

    // Open file in write mode
    file = fopen("MazeGame.SHAPE", "w");

    // Check if file is opened successfully
    if (file == NULL) {
        printf("Error: Unable to create file.\n");
        return 1;
    }

    // Write dimensions and maze content to the file
    for (i = 0; i < ROWS; i++) {
        for (j = 0; j < COLS; j++) {
            fputc('#', file); // Write '#' to the file
        }
        fputc('\n', file); // Write a newline character
    }

    // Close the file
    fclose(file);


    return 0;
}